name: Deploy to Cloud Run

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: clans-api
  REGION: europe-west1
  SQL_INSTANCE: us-central1-c:vertigo-master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write' # For gcp auth

    steps:
    # 1. Cloning repo
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2. GCP Authentication
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # 3. Gcloud CLI Installation
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

  # 4. Docker imajını build et ve Artifact Registry'e pushla Building Docker Image and upload to Artifact Registry
    - name: Build and Push Docker Image
      run: |-
        gcloud auth configure-docker europe-west1-docker.pkg.dev  # REPO BÖLGESİNİ DEĞİŞTİREBİLİRSİNİZ
        docker build -t "europe-west1-docker.pkg.dev/$PROJECT_ID/clans-service/$SERVICE_NAME:$GITHUB_SHA" .
        docker push "europe-west1-docker.pkg.dev/$PROJECT_ID/clans-service/$SERVICE_NAME:$GITHUB_SHA"

    # 5. Deploying on Cloud Run
    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --image "europe-west1-docker.pkg.dev/$PROJECT_ID/clans-service/$SERVICE_NAME:$GITHUB_SHA" \
          --platform managed \
          --region "$REGION" \
          --allow-unauthenticated \
          --cpu 1 \
          --memory 512Mi \
          --max-instances 3 \
          --set-cloudsql-instances "$PROJECT_ID:$SQL_INSTANCE" \
          --update-env-vars "DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
          --project "$PROJECT_ID"